// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2xMk-g1E6LUCETDeUerEzs-jgAzgMLyE',
    appId: '1:777372022894:web:5c5e402dc40d7ce1878e7f',
    messagingSenderId: '777372022894',
    projectId: 'dio-package',
    authDomain: 'dio-package.firebaseapp.com',
    storageBucket: 'dio-package.firebasestorage.app',
    measurementId: 'G-6DG2GNSS0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt5LEeKJ5p1Pk6X6TtoRtGSPzhXMn3nw0',
    appId: '1:777372022894:android:8bb47eae338eefac878e7f',
    messagingSenderId: '777372022894',
    projectId: 'dio-package',
    storageBucket: 'dio-package.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwNR4bGEQsX1a8M3Tbbg-wp_B4R6U1B_8',
    appId: '1:777372022894:ios:1ed09a5093234e37878e7f',
    messagingSenderId: '777372022894',
    projectId: 'dio-package',
    storageBucket: 'dio-package.firebasestorage.app',
    iosBundleId: 'com.example.dioPackage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwNR4bGEQsX1a8M3Tbbg-wp_B4R6U1B_8',
    appId: '1:777372022894:ios:1ed09a5093234e37878e7f',
    messagingSenderId: '777372022894',
    projectId: 'dio-package',
    storageBucket: 'dio-package.firebasestorage.app',
    iosBundleId: 'com.example.dioPackage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2xMk-g1E6LUCETDeUerEzs-jgAzgMLyE',
    appId: '1:777372022894:web:60c23fd9547b6e78878e7f',
    messagingSenderId: '777372022894',
    projectId: 'dio-package',
    authDomain: 'dio-package.firebaseapp.com',
    storageBucket: 'dio-package.firebasestorage.app',
    measurementId: 'G-0NZXM9DVEJ',
  );
}
